# coding: utf-8 
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from compute.v1 import dc2_pb2 as compute_dot_v1_dot_dc2__pb2


class Dc2Stub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListDc2 = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/ListDc2',
        request_serializer=compute_dot_v1_dot_dc2__pb2.ListDc2Request.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.ListDc2Response.FromString,
        )
    self.GetDc2TotalCnt = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/GetDc2TotalCnt',
        request_serializer=compute_dot_v1_dot_dc2__pb2.GetDc2TotalCntRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.GetDc2TotalCntResponse.FromString,
        )
    self.GetDc2ByUuid = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/GetDc2ByUuid',
        request_serializer=compute_dot_v1_dot_dc2__pb2.GetDc2ByUuidRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.GetDc2ByUuidResponse.FromString,
        )
    self.StartDc2 = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/StartDc2',
        request_serializer=compute_dot_v1_dot_dc2__pb2.StartDc2Request.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.StartDc2Response.FromString,
        )
    self.StopDc2 = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/StopDc2',
        request_serializer=compute_dot_v1_dot_dc2__pb2.StopDc2Request.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.StopDc2Response.FromString,
        )
    self.RebootDc2 = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/RebootDc2',
        request_serializer=compute_dot_v1_dot_dc2__pb2.RebootDc2Request.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.RebootDc2Response.FromString,
        )
    self.DestroyDc2 = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/DestroyDc2',
        request_serializer=compute_dot_v1_dot_dc2__pb2.DestroyDc2Request.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.DestroyDc2Response.FromString,
        )
    self.ChangeDc2Name = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/ChangeDc2Name',
        request_serializer=compute_dot_v1_dot_dc2__pb2.ChangeDc2NameRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.ChangeDc2NameResponse.FromString,
        )
    self.ChangeDc2Password = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/ChangeDc2Password',
        request_serializer=compute_dot_v1_dot_dc2__pb2.ChangeDc2PasswordRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.ChangeDc2PasswordResponse.FromString,
        )
    self.ReinstallDc2System = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/ReinstallDc2System',
        request_serializer=compute_dot_v1_dot_dc2__pb2.ReinstallDc2SystemRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.ReinstallDc2SystemResponse.FromString,
        )
    self.CreateDc2 = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/CreateDc2',
        request_serializer=compute_dot_v1_dot_dc2__pb2.CreateDc2Request.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.CreateDc2Response.FromString,
        )
    self.ChangeDc2Spec = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/ChangeDc2Spec',
        request_serializer=compute_dot_v1_dot_dc2__pb2.ChangeDc2SpecRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.ChangeDc2SpecResponse.FromString,
        )
    self.ListImage = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/ListImage',
        request_serializer=compute_dot_v1_dot_dc2__pb2.ListImageRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.ListImageResponse.FromString,
        )
    self.ListSshKey = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/ListSshKey',
        request_serializer=compute_dot_v1_dot_dc2__pb2.ListSshKeyRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.ListSshKeyResponse.FromString,
        )
    self.CreateSshKey = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/CreateSshKey',
        request_serializer=compute_dot_v1_dot_dc2__pb2.CreateSshKeyRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.CreateSshKeyResponse.FromString,
        )
    self.DeleteSshKey = channel.unary_unary(
        '/didi.cloud.compute.v1.Dc2/DeleteSshKey',
        request_serializer=compute_dot_v1_dot_dc2__pb2.DeleteSshKeyRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_dc2__pb2.DeleteSshKeyResponse.FromString,
        )


class Dc2Servicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListDc2(self, request, context):
    """获取dc2列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDc2TotalCnt(self, request, context):
    """获取dc2数量
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDc2ByUuid(self, request, context):
    """根据uuid获取dc2
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartDc2(self, request, context):
    """dc2开机
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopDc2(self, request, context):
    """dc2关机
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RebootDc2(self, request, context):
    """dc2重启
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DestroyDc2(self, request, context):
    """删除dc2
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangeDc2Name(self, request, context):
    """更改dc2名称
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangeDc2Password(self, request, context):
    """更改dc2密码
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReinstallDc2System(self, request, context):
    """重装dc2系统
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateDc2(self, request, context):
    """创建dc2
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangeDc2Spec(self, request, context):
    """更改dc2配置
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListImage(self, request, context):
    """获取image列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListSshKey(self, request, context):
    """获取sshkey列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateSshKey(self, request, context):
    """创建sshkey
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSshKey(self, request, context):
    """删除sshkey
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Dc2Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListDc2': grpc.unary_unary_rpc_method_handler(
          servicer.ListDc2,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.ListDc2Request.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.ListDc2Response.SerializeToString,
      ),
      'GetDc2TotalCnt': grpc.unary_unary_rpc_method_handler(
          servicer.GetDc2TotalCnt,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.GetDc2TotalCntRequest.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.GetDc2TotalCntResponse.SerializeToString,
      ),
      'GetDc2ByUuid': grpc.unary_unary_rpc_method_handler(
          servicer.GetDc2ByUuid,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.GetDc2ByUuidRequest.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.GetDc2ByUuidResponse.SerializeToString,
      ),
      'StartDc2': grpc.unary_unary_rpc_method_handler(
          servicer.StartDc2,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.StartDc2Request.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.StartDc2Response.SerializeToString,
      ),
      'StopDc2': grpc.unary_unary_rpc_method_handler(
          servicer.StopDc2,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.StopDc2Request.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.StopDc2Response.SerializeToString,
      ),
      'RebootDc2': grpc.unary_unary_rpc_method_handler(
          servicer.RebootDc2,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.RebootDc2Request.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.RebootDc2Response.SerializeToString,
      ),
      'DestroyDc2': grpc.unary_unary_rpc_method_handler(
          servicer.DestroyDc2,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.DestroyDc2Request.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.DestroyDc2Response.SerializeToString,
      ),
      'ChangeDc2Name': grpc.unary_unary_rpc_method_handler(
          servicer.ChangeDc2Name,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.ChangeDc2NameRequest.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.ChangeDc2NameResponse.SerializeToString,
      ),
      'ChangeDc2Password': grpc.unary_unary_rpc_method_handler(
          servicer.ChangeDc2Password,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.ChangeDc2PasswordRequest.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.ChangeDc2PasswordResponse.SerializeToString,
      ),
      'ReinstallDc2System': grpc.unary_unary_rpc_method_handler(
          servicer.ReinstallDc2System,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.ReinstallDc2SystemRequest.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.ReinstallDc2SystemResponse.SerializeToString,
      ),
      'CreateDc2': grpc.unary_unary_rpc_method_handler(
          servicer.CreateDc2,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.CreateDc2Request.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.CreateDc2Response.SerializeToString,
      ),
      'ChangeDc2Spec': grpc.unary_unary_rpc_method_handler(
          servicer.ChangeDc2Spec,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.ChangeDc2SpecRequest.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.ChangeDc2SpecResponse.SerializeToString,
      ),
      'ListImage': grpc.unary_unary_rpc_method_handler(
          servicer.ListImage,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.ListImageRequest.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.ListImageResponse.SerializeToString,
      ),
      'ListSshKey': grpc.unary_unary_rpc_method_handler(
          servicer.ListSshKey,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.ListSshKeyRequest.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.ListSshKeyResponse.SerializeToString,
      ),
      'CreateSshKey': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSshKey,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.CreateSshKeyRequest.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.CreateSshKeyResponse.SerializeToString,
      ),
      'DeleteSshKey': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSshKey,
          request_deserializer=compute_dot_v1_dot_dc2__pb2.DeleteSshKeyRequest.FromString,
          response_serializer=compute_dot_v1_dot_dc2__pb2.DeleteSshKeyResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'didi.cloud.compute.v1.Dc2', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
