# coding: utf-8 
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from compute.v1 import eip_pb2 as compute_dot_v1_dot_eip__pb2


class EipStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListEip = channel.unary_unary(
        '/didi.cloud.compute.v1.Eip/ListEip',
        request_serializer=compute_dot_v1_dot_eip__pb2.ListEipRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_eip__pb2.ListEipResponse.FromString,
        )
    self.GetEipTotalCnt = channel.unary_unary(
        '/didi.cloud.compute.v1.Eip/GetEipTotalCnt',
        request_serializer=compute_dot_v1_dot_eip__pb2.GetEipTotalCntRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_eip__pb2.GetEipTotalCntResponse.FromString,
        )
    self.GetEipByUuid = channel.unary_unary(
        '/didi.cloud.compute.v1.Eip/GetEipByUuid',
        request_serializer=compute_dot_v1_dot_eip__pb2.GetEipByUuidRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_eip__pb2.GetEipByUuidResponse.FromString,
        )
    self.CreateEip = channel.unary_unary(
        '/didi.cloud.compute.v1.Eip/CreateEip',
        request_serializer=compute_dot_v1_dot_eip__pb2.CreateEipRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_eip__pb2.CreateEipResponse.FromString,
        )
    self.ChangeEipBandwidth = channel.unary_unary(
        '/didi.cloud.compute.v1.Eip/ChangeEipBandwidth',
        request_serializer=compute_dot_v1_dot_eip__pb2.ChangeEipBandwidthRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_eip__pb2.ChangeEipBandwidthResponse.FromString,
        )
    self.DeleteEip = channel.unary_unary(
        '/didi.cloud.compute.v1.Eip/DeleteEip',
        request_serializer=compute_dot_v1_dot_eip__pb2.DeleteEipRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_eip__pb2.DeleteEipResponse.FromString,
        )
    self.AttachEipToDc2 = channel.unary_unary(
        '/didi.cloud.compute.v1.Eip/AttachEipToDc2',
        request_serializer=compute_dot_v1_dot_eip__pb2.AttachEipToDc2Request.SerializeToString,
        response_deserializer=compute_dot_v1_dot_eip__pb2.AttachEipToDc2Response.FromString,
        )
    self.DetachEipFromDc2 = channel.unary_unary(
        '/didi.cloud.compute.v1.Eip/DetachEipFromDc2',
        request_serializer=compute_dot_v1_dot_eip__pb2.DetachEipFromDc2Request.SerializeToString,
        response_deserializer=compute_dot_v1_dot_eip__pb2.DetachEipFromDc2Response.FromString,
        )


class EipServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListEip(self, request, context):
    """获取eip列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEipTotalCnt(self, request, context):
    """获取eip数量
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEipByUuid(self, request, context):
    """根据uuid获取eip
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateEip(self, request, context):
    """创建eip
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangeEipBandwidth(self, request, context):
    """更改eip带宽
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteEip(self, request, context):
    """删除eip
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AttachEipToDc2(self, request, context):
    """绑定eip到dc2
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DetachEipFromDc2(self, request, context):
    """从dc2解绑eip
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EipServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListEip': grpc.unary_unary_rpc_method_handler(
          servicer.ListEip,
          request_deserializer=compute_dot_v1_dot_eip__pb2.ListEipRequest.FromString,
          response_serializer=compute_dot_v1_dot_eip__pb2.ListEipResponse.SerializeToString,
      ),
      'GetEipTotalCnt': grpc.unary_unary_rpc_method_handler(
          servicer.GetEipTotalCnt,
          request_deserializer=compute_dot_v1_dot_eip__pb2.GetEipTotalCntRequest.FromString,
          response_serializer=compute_dot_v1_dot_eip__pb2.GetEipTotalCntResponse.SerializeToString,
      ),
      'GetEipByUuid': grpc.unary_unary_rpc_method_handler(
          servicer.GetEipByUuid,
          request_deserializer=compute_dot_v1_dot_eip__pb2.GetEipByUuidRequest.FromString,
          response_serializer=compute_dot_v1_dot_eip__pb2.GetEipByUuidResponse.SerializeToString,
      ),
      'CreateEip': grpc.unary_unary_rpc_method_handler(
          servicer.CreateEip,
          request_deserializer=compute_dot_v1_dot_eip__pb2.CreateEipRequest.FromString,
          response_serializer=compute_dot_v1_dot_eip__pb2.CreateEipResponse.SerializeToString,
      ),
      'ChangeEipBandwidth': grpc.unary_unary_rpc_method_handler(
          servicer.ChangeEipBandwidth,
          request_deserializer=compute_dot_v1_dot_eip__pb2.ChangeEipBandwidthRequest.FromString,
          response_serializer=compute_dot_v1_dot_eip__pb2.ChangeEipBandwidthResponse.SerializeToString,
      ),
      'DeleteEip': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteEip,
          request_deserializer=compute_dot_v1_dot_eip__pb2.DeleteEipRequest.FromString,
          response_serializer=compute_dot_v1_dot_eip__pb2.DeleteEipResponse.SerializeToString,
      ),
      'AttachEipToDc2': grpc.unary_unary_rpc_method_handler(
          servicer.AttachEipToDc2,
          request_deserializer=compute_dot_v1_dot_eip__pb2.AttachEipToDc2Request.FromString,
          response_serializer=compute_dot_v1_dot_eip__pb2.AttachEipToDc2Response.SerializeToString,
      ),
      'DetachEipFromDc2': grpc.unary_unary_rpc_method_handler(
          servicer.DetachEipFromDc2,
          request_deserializer=compute_dot_v1_dot_eip__pb2.DetachEipFromDc2Request.FromString,
          response_serializer=compute_dot_v1_dot_eip__pb2.DetachEipFromDc2Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'didi.cloud.compute.v1.Eip', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
