# coding: utf-8 
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from compute.v1 import sg_pb2 as compute_dot_v1_dot_sg__pb2


class SgStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListSg = channel.unary_unary(
        '/didi.cloud.compute.v1.Sg/ListSg',
        request_serializer=compute_dot_v1_dot_sg__pb2.ListSgRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_sg__pb2.ListSgResponse.FromString,
        )
    self.GetSgTotalCnt = channel.unary_unary(
        '/didi.cloud.compute.v1.Sg/GetSgTotalCnt',
        request_serializer=compute_dot_v1_dot_sg__pb2.GetSgTotalCntRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_sg__pb2.GetSgTotalCntResponse.FromString,
        )
    self.CreateSg = channel.unary_unary(
        '/didi.cloud.compute.v1.Sg/CreateSg',
        request_serializer=compute_dot_v1_dot_sg__pb2.CreateSgRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_sg__pb2.CreateSgResponse.FromString,
        )
    self.DeleteSg = channel.unary_unary(
        '/didi.cloud.compute.v1.Sg/DeleteSg',
        request_serializer=compute_dot_v1_dot_sg__pb2.DeleteSgRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_sg__pb2.DeleteSgResponse.FromString,
        )
    self.AttachDc2ToSg = channel.unary_unary(
        '/didi.cloud.compute.v1.Sg/AttachDc2ToSg',
        request_serializer=compute_dot_v1_dot_sg__pb2.AttachDc2ToSgRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_sg__pb2.AttachDc2ToSgResponse.FromString,
        )
    self.DetachDc2FromSg = channel.unary_unary(
        '/didi.cloud.compute.v1.Sg/DetachDc2FromSg',
        request_serializer=compute_dot_v1_dot_sg__pb2.DetachDc2FromSgRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_sg__pb2.DetachDc2FromSgResponse.FromString,
        )
    self.ChangeSgName = channel.unary_unary(
        '/didi.cloud.compute.v1.Sg/ChangeSgName',
        request_serializer=compute_dot_v1_dot_sg__pb2.ChangeSgNameRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_sg__pb2.ChangeSgNameResponse.FromString,
        )
    self.ListSgRule = channel.unary_unary(
        '/didi.cloud.compute.v1.Sg/ListSgRule',
        request_serializer=compute_dot_v1_dot_sg__pb2.ListSgRuleRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_sg__pb2.ListSgRuleResponse.FromString,
        )
    self.GetSgRuleTotalCnt = channel.unary_unary(
        '/didi.cloud.compute.v1.Sg/GetSgRuleTotalCnt',
        request_serializer=compute_dot_v1_dot_sg__pb2.GetSgRuleTotalCntRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_sg__pb2.GetSgRuleTotalCntResponse.FromString,
        )
    self.CreateSgRule = channel.unary_unary(
        '/didi.cloud.compute.v1.Sg/CreateSgRule',
        request_serializer=compute_dot_v1_dot_sg__pb2.CreateSgRuleRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_sg__pb2.CreateSgRuleResponse.FromString,
        )
    self.DeleteSgRule = channel.unary_unary(
        '/didi.cloud.compute.v1.Sg/DeleteSgRule',
        request_serializer=compute_dot_v1_dot_sg__pb2.DeleteSgRuleRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_sg__pb2.DeleteSgRuleResponse.FromString,
        )


class SgServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListSg(self, request, context):
    """获取SG列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSgTotalCnt(self, request, context):
    """获取SG总量
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateSg(self, request, context):
    """创建SG
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSg(self, request, context):
    """删除SG
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AttachDc2ToSg(self, request, context):
    """绑定DC2到SG
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DetachDc2FromSg(self, request, context):
    """从SG解绑DC2
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangeSgName(self, request, context):
    """更改SG名称
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListSgRule(self, request, context):
    """获取SGRule列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSgRuleTotalCnt(self, request, context):
    """获取SGRule总量
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateSgRule(self, request, context):
    """创建SGRule
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSgRule(self, request, context):
    """删除SGRule
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SgServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListSg': grpc.unary_unary_rpc_method_handler(
          servicer.ListSg,
          request_deserializer=compute_dot_v1_dot_sg__pb2.ListSgRequest.FromString,
          response_serializer=compute_dot_v1_dot_sg__pb2.ListSgResponse.SerializeToString,
      ),
      'GetSgTotalCnt': grpc.unary_unary_rpc_method_handler(
          servicer.GetSgTotalCnt,
          request_deserializer=compute_dot_v1_dot_sg__pb2.GetSgTotalCntRequest.FromString,
          response_serializer=compute_dot_v1_dot_sg__pb2.GetSgTotalCntResponse.SerializeToString,
      ),
      'CreateSg': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSg,
          request_deserializer=compute_dot_v1_dot_sg__pb2.CreateSgRequest.FromString,
          response_serializer=compute_dot_v1_dot_sg__pb2.CreateSgResponse.SerializeToString,
      ),
      'DeleteSg': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSg,
          request_deserializer=compute_dot_v1_dot_sg__pb2.DeleteSgRequest.FromString,
          response_serializer=compute_dot_v1_dot_sg__pb2.DeleteSgResponse.SerializeToString,
      ),
      'AttachDc2ToSg': grpc.unary_unary_rpc_method_handler(
          servicer.AttachDc2ToSg,
          request_deserializer=compute_dot_v1_dot_sg__pb2.AttachDc2ToSgRequest.FromString,
          response_serializer=compute_dot_v1_dot_sg__pb2.AttachDc2ToSgResponse.SerializeToString,
      ),
      'DetachDc2FromSg': grpc.unary_unary_rpc_method_handler(
          servicer.DetachDc2FromSg,
          request_deserializer=compute_dot_v1_dot_sg__pb2.DetachDc2FromSgRequest.FromString,
          response_serializer=compute_dot_v1_dot_sg__pb2.DetachDc2FromSgResponse.SerializeToString,
      ),
      'ChangeSgName': grpc.unary_unary_rpc_method_handler(
          servicer.ChangeSgName,
          request_deserializer=compute_dot_v1_dot_sg__pb2.ChangeSgNameRequest.FromString,
          response_serializer=compute_dot_v1_dot_sg__pb2.ChangeSgNameResponse.SerializeToString,
      ),
      'ListSgRule': grpc.unary_unary_rpc_method_handler(
          servicer.ListSgRule,
          request_deserializer=compute_dot_v1_dot_sg__pb2.ListSgRuleRequest.FromString,
          response_serializer=compute_dot_v1_dot_sg__pb2.ListSgRuleResponse.SerializeToString,
      ),
      'GetSgRuleTotalCnt': grpc.unary_unary_rpc_method_handler(
          servicer.GetSgRuleTotalCnt,
          request_deserializer=compute_dot_v1_dot_sg__pb2.GetSgRuleTotalCntRequest.FromString,
          response_serializer=compute_dot_v1_dot_sg__pb2.GetSgRuleTotalCntResponse.SerializeToString,
      ),
      'CreateSgRule': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSgRule,
          request_deserializer=compute_dot_v1_dot_sg__pb2.CreateSgRuleRequest.FromString,
          response_serializer=compute_dot_v1_dot_sg__pb2.CreateSgRuleResponse.SerializeToString,
      ),
      'DeleteSgRule': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSgRule,
          request_deserializer=compute_dot_v1_dot_sg__pb2.DeleteSgRuleRequest.FromString,
          response_serializer=compute_dot_v1_dot_sg__pb2.DeleteSgRuleResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'didi.cloud.compute.v1.Sg', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
