# coding: utf-8 
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from compute.v1 import vpc_pb2 as compute_dot_v1_dot_vpc__pb2


class VpcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListVpc = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/ListVpc',
        request_serializer=compute_dot_v1_dot_vpc__pb2.ListVpcRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.ListVpcResponse.FromString,
        )
    self.GetVpcByUuid = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/GetVpcByUuid',
        request_serializer=compute_dot_v1_dot_vpc__pb2.GetVpcByUuidRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.GetVpcByUuidResponse.FromString,
        )
    self.GetVpcTotalCnt = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/GetVpcTotalCnt',
        request_serializer=compute_dot_v1_dot_vpc__pb2.GetVpcTotalCntRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.GetVpcTotalCntResponse.FromString,
        )
    self.CreateVpc = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/CreateVpc',
        request_serializer=compute_dot_v1_dot_vpc__pb2.CreateVpcRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.CreateVpcResponse.FromString,
        )
    self.DeleteVpc = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/DeleteVpc',
        request_serializer=compute_dot_v1_dot_vpc__pb2.DeleteVpcRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.DeleteVpcResponse.FromString,
        )
    self.ChangeVpcName = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/ChangeVpcName',
        request_serializer=compute_dot_v1_dot_vpc__pb2.ChangeVpcNameRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.ChangeVpcNameResponse.FromString,
        )
    self.ListVpcAvailableCidr = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/ListVpcAvailableCidr',
        request_serializer=compute_dot_v1_dot_vpc__pb2.ListVpcAvailableCidrRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.ListVpcAvailableCidrResponse.FromString,
        )
    self.ListSubnet = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/ListSubnet',
        request_serializer=compute_dot_v1_dot_vpc__pb2.ListSubnetRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.ListSubnetResponse.FromString,
        )
    self.GetSubnetByUuid = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/GetSubnetByUuid',
        request_serializer=compute_dot_v1_dot_vpc__pb2.GetSubnetByUuidRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.GetSubnetByUuidResponse.FromString,
        )
    self.GetSubnetTotalCnt = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/GetSubnetTotalCnt',
        request_serializer=compute_dot_v1_dot_vpc__pb2.GetSubnetTotalCntRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.GetSubnetTotalCntResponse.FromString,
        )
    self.CreateSubnet = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/CreateSubnet',
        request_serializer=compute_dot_v1_dot_vpc__pb2.CreateSubnetRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.CreateSubnetResponse.FromString,
        )
    self.DeleteSubnet = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/DeleteSubnet',
        request_serializer=compute_dot_v1_dot_vpc__pb2.DeleteSubnetRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.DeleteSubnetResponse.FromString,
        )
    self.ChangeSubnetName = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/ChangeSubnetName',
        request_serializer=compute_dot_v1_dot_vpc__pb2.ChangeSubnetNameRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.ChangeSubnetNameResponse.FromString,
        )
    self.CheckSubnetCidrOverlap = channel.unary_unary(
        '/didi.cloud.compute.v1.Vpc/CheckSubnetCidrOverlap',
        request_serializer=compute_dot_v1_dot_vpc__pb2.CheckSubnetCidrOverlapRequest.SerializeToString,
        response_deserializer=compute_dot_v1_dot_vpc__pb2.CheckSubnetCidrOverlapResponse.FromString,
        )


class VpcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListVpc(self, request, context):
    """获取vpc列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVpcByUuid(self, request, context):
    """根据uuid获取vpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVpcTotalCnt(self, request, context):
    """获取vpc数量
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateVpc(self, request, context):
    """创建vpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteVpc(self, request, context):
    """删除vpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangeVpcName(self, request, context):
    """改名vpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListVpcAvailableCidr(self, request, context):
    """获取可用网段
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListSubnet(self, request, context):
    """获取subnet列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSubnetByUuid(self, request, context):
    """根据uuid获取subnet
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSubnetTotalCnt(self, request, context):
    """获取subnet数量
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateSubnet(self, request, context):
    """创建subnet
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSubnet(self, request, context):
    """删除subnet
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangeSubnetName(self, request, context):
    """改名subnet
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckSubnetCidrOverlap(self, request, context):
    """检查subnet所在vpc内子网网段是否有重叠
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListVpc': grpc.unary_unary_rpc_method_handler(
          servicer.ListVpc,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.ListVpcRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.ListVpcResponse.SerializeToString,
      ),
      'GetVpcByUuid': grpc.unary_unary_rpc_method_handler(
          servicer.GetVpcByUuid,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.GetVpcByUuidRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.GetVpcByUuidResponse.SerializeToString,
      ),
      'GetVpcTotalCnt': grpc.unary_unary_rpc_method_handler(
          servicer.GetVpcTotalCnt,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.GetVpcTotalCntRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.GetVpcTotalCntResponse.SerializeToString,
      ),
      'CreateVpc': grpc.unary_unary_rpc_method_handler(
          servicer.CreateVpc,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.CreateVpcRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.CreateVpcResponse.SerializeToString,
      ),
      'DeleteVpc': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteVpc,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.DeleteVpcRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.DeleteVpcResponse.SerializeToString,
      ),
      'ChangeVpcName': grpc.unary_unary_rpc_method_handler(
          servicer.ChangeVpcName,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.ChangeVpcNameRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.ChangeVpcNameResponse.SerializeToString,
      ),
      'ListVpcAvailableCidr': grpc.unary_unary_rpc_method_handler(
          servicer.ListVpcAvailableCidr,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.ListVpcAvailableCidrRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.ListVpcAvailableCidrResponse.SerializeToString,
      ),
      'ListSubnet': grpc.unary_unary_rpc_method_handler(
          servicer.ListSubnet,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.ListSubnetRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.ListSubnetResponse.SerializeToString,
      ),
      'GetSubnetByUuid': grpc.unary_unary_rpc_method_handler(
          servicer.GetSubnetByUuid,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.GetSubnetByUuidRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.GetSubnetByUuidResponse.SerializeToString,
      ),
      'GetSubnetTotalCnt': grpc.unary_unary_rpc_method_handler(
          servicer.GetSubnetTotalCnt,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.GetSubnetTotalCntRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.GetSubnetTotalCntResponse.SerializeToString,
      ),
      'CreateSubnet': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSubnet,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.CreateSubnetRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.CreateSubnetResponse.SerializeToString,
      ),
      'DeleteSubnet': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSubnet,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.DeleteSubnetRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.DeleteSubnetResponse.SerializeToString,
      ),
      'ChangeSubnetName': grpc.unary_unary_rpc_method_handler(
          servicer.ChangeSubnetName,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.ChangeSubnetNameRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.ChangeSubnetNameResponse.SerializeToString,
      ),
      'CheckSubnetCidrOverlap': grpc.unary_unary_rpc_method_handler(
          servicer.CheckSubnetCidrOverlap,
          request_deserializer=compute_dot_v1_dot_vpc__pb2.CheckSubnetCidrOverlapRequest.FromString,
          response_serializer=compute_dot_v1_dot_vpc__pb2.CheckSubnetCidrOverlapResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'didi.cloud.compute.v1.Vpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
