# coding: utf-8 
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from monitor.v1 import counter_pb2 as monitor_dot_v1_dot_counter__pb2


class MonitorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListCounter = channel.unary_unary(
        '/didi.cloud.monitor.v1.Monitor/ListCounter',
        request_serializer=monitor_dot_v1_dot_counter__pb2.ListCounterRequest.SerializeToString,
        response_deserializer=monitor_dot_v1_dot_counter__pb2.ListCounterResponse.FromString,
        )
    self.ListCounterData = channel.unary_unary(
        '/didi.cloud.monitor.v1.Monitor/ListCounterData',
        request_serializer=monitor_dot_v1_dot_counter__pb2.ListCounterDataRequest.SerializeToString,
        response_deserializer=monitor_dot_v1_dot_counter__pb2.ListCounterDataResponse.FromString,
        )


class MonitorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListCounter(self, request, context):
    """获取曲线列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListCounterData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MonitorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListCounter': grpc.unary_unary_rpc_method_handler(
          servicer.ListCounter,
          request_deserializer=monitor_dot_v1_dot_counter__pb2.ListCounterRequest.FromString,
          response_serializer=monitor_dot_v1_dot_counter__pb2.ListCounterResponse.SerializeToString,
      ),
      'ListCounterData': grpc.unary_unary_rpc_method_handler(
          servicer.ListCounterData,
          request_deserializer=monitor_dot_v1_dot_counter__pb2.ListCounterDataRequest.FromString,
          response_serializer=monitor_dot_v1_dot_counter__pb2.ListCounterDataResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'didi.cloud.monitor.v1.Monitor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
