# coding: utf-8 
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from bill.v1 import bill_pb2 as bill_dot_v1_dot_bill__pb2


class BillStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ContinueList = channel.unary_unary(
        '/didi.cloud.bill.v1.Bill/ContinueList',
        request_serializer=bill_dot_v1_dot_bill__pb2.ContinueListRequest.SerializeToString,
        response_deserializer=bill_dot_v1_dot_bill__pb2.ContinueListResponse.FromString,
        )
    self.ContinueMonthly = channel.unary_unary(
        '/didi.cloud.bill.v1.Bill/ContinueMonthly',
        request_serializer=bill_dot_v1_dot_bill__pb2.ContinueMonthlyRequest.SerializeToString,
        response_deserializer=bill_dot_v1_dot_bill__pb2.ContinueMonthlyResponse.FromString,
        )
    self.ChangeToMonthly = channel.unary_unary(
        '/didi.cloud.bill.v1.Bill/ChangeToMonthly',
        request_serializer=bill_dot_v1_dot_bill__pb2.ChangeToMonthlyRequest.SerializeToString,
        response_deserializer=bill_dot_v1_dot_bill__pb2.ChangeToMonthlyResponse.FromString,
        )
    self.ChangeExpireStrategy = channel.unary_unary(
        '/didi.cloud.bill.v1.Bill/ChangeExpireStrategy',
        request_serializer=bill_dot_v1_dot_bill__pb2.ChangeExpireStrategyRequest.SerializeToString,
        response_deserializer=bill_dot_v1_dot_bill__pb2.ChangeExpireStrategyResponse.FromString,
        )
    self.CheckDc2Price = channel.unary_unary(
        '/didi.cloud.bill.v1.Bill/CheckDc2Price',
        request_serializer=bill_dot_v1_dot_bill__pb2.CheckDc2PriceRequest.SerializeToString,
        response_deserializer=bill_dot_v1_dot_bill__pb2.CheckPriceResponse.FromString,
        )
    self.CheckEipPrice = channel.unary_unary(
        '/didi.cloud.bill.v1.Bill/CheckEipPrice',
        request_serializer=bill_dot_v1_dot_bill__pb2.CheckEipPriceRequest.SerializeToString,
        response_deserializer=bill_dot_v1_dot_bill__pb2.CheckPriceResponse.FromString,
        )
    self.CheckEbsPrice = channel.unary_unary(
        '/didi.cloud.bill.v1.Bill/CheckEbsPrice',
        request_serializer=bill_dot_v1_dot_bill__pb2.CheckEbsPriceRequest.SerializeToString,
        response_deserializer=bill_dot_v1_dot_bill__pb2.CheckPriceResponse.FromString,
        )
    self.GetDc2ChargeInfoAndSpec = channel.unary_unary(
        '/didi.cloud.bill.v1.Bill/GetDc2ChargeInfoAndSpec',
        request_serializer=bill_dot_v1_dot_bill__pb2.GetChargeInfoAndSpecRequest.SerializeToString,
        response_deserializer=bill_dot_v1_dot_bill__pb2.GetDc2ChargeInfoAndSpecResponse.FromString,
        )
    self.GetEipChargeInfoAndSpec = channel.unary_unary(
        '/didi.cloud.bill.v1.Bill/GetEipChargeInfoAndSpec',
        request_serializer=bill_dot_v1_dot_bill__pb2.GetChargeInfoAndSpecRequest.SerializeToString,
        response_deserializer=bill_dot_v1_dot_bill__pb2.GetEipChargeInfoAndSpecResponse.FromString,
        )
    self.GetEbsChargeInfoAndSpec = channel.unary_unary(
        '/didi.cloud.bill.v1.Bill/GetEbsChargeInfoAndSpec',
        request_serializer=bill_dot_v1_dot_bill__pb2.GetChargeInfoAndSpecRequest.SerializeToString,
        response_deserializer=bill_dot_v1_dot_bill__pb2.GetEbsChargeInfoAndSpecResponse.FromString,
        )


class BillServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ContinueList(self, request, context):
    """获取待续费资源列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ContinueMonthly(self, request, context):
    """批量续费包月资源
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangeToMonthly(self, request, context):
    """批量将按时长资源转为包月
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangeExpireStrategy(self, request, context):
    """更改资源到期策略
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckDc2Price(self, request, context):
    """DC2询价
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckEipPrice(self, request, context):
    """EIP询价
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckEbsPrice(self, request, context):
    """EBS询价
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDc2ChargeInfoAndSpec(self, request, context):
    """DC2查询计费与规格信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEipChargeInfoAndSpec(self, request, context):
    """EIP查询计费与规格信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEbsChargeInfoAndSpec(self, request, context):
    """EBS查询计费与规格信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BillServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ContinueList': grpc.unary_unary_rpc_method_handler(
          servicer.ContinueList,
          request_deserializer=bill_dot_v1_dot_bill__pb2.ContinueListRequest.FromString,
          response_serializer=bill_dot_v1_dot_bill__pb2.ContinueListResponse.SerializeToString,
      ),
      'ContinueMonthly': grpc.unary_unary_rpc_method_handler(
          servicer.ContinueMonthly,
          request_deserializer=bill_dot_v1_dot_bill__pb2.ContinueMonthlyRequest.FromString,
          response_serializer=bill_dot_v1_dot_bill__pb2.ContinueMonthlyResponse.SerializeToString,
      ),
      'ChangeToMonthly': grpc.unary_unary_rpc_method_handler(
          servicer.ChangeToMonthly,
          request_deserializer=bill_dot_v1_dot_bill__pb2.ChangeToMonthlyRequest.FromString,
          response_serializer=bill_dot_v1_dot_bill__pb2.ChangeToMonthlyResponse.SerializeToString,
      ),
      'ChangeExpireStrategy': grpc.unary_unary_rpc_method_handler(
          servicer.ChangeExpireStrategy,
          request_deserializer=bill_dot_v1_dot_bill__pb2.ChangeExpireStrategyRequest.FromString,
          response_serializer=bill_dot_v1_dot_bill__pb2.ChangeExpireStrategyResponse.SerializeToString,
      ),
      'CheckDc2Price': grpc.unary_unary_rpc_method_handler(
          servicer.CheckDc2Price,
          request_deserializer=bill_dot_v1_dot_bill__pb2.CheckDc2PriceRequest.FromString,
          response_serializer=bill_dot_v1_dot_bill__pb2.CheckPriceResponse.SerializeToString,
      ),
      'CheckEipPrice': grpc.unary_unary_rpc_method_handler(
          servicer.CheckEipPrice,
          request_deserializer=bill_dot_v1_dot_bill__pb2.CheckEipPriceRequest.FromString,
          response_serializer=bill_dot_v1_dot_bill__pb2.CheckPriceResponse.SerializeToString,
      ),
      'CheckEbsPrice': grpc.unary_unary_rpc_method_handler(
          servicer.CheckEbsPrice,
          request_deserializer=bill_dot_v1_dot_bill__pb2.CheckEbsPriceRequest.FromString,
          response_serializer=bill_dot_v1_dot_bill__pb2.CheckPriceResponse.SerializeToString,
      ),
      'GetDc2ChargeInfoAndSpec': grpc.unary_unary_rpc_method_handler(
          servicer.GetDc2ChargeInfoAndSpec,
          request_deserializer=bill_dot_v1_dot_bill__pb2.GetChargeInfoAndSpecRequest.FromString,
          response_serializer=bill_dot_v1_dot_bill__pb2.GetDc2ChargeInfoAndSpecResponse.SerializeToString,
      ),
      'GetEipChargeInfoAndSpec': grpc.unary_unary_rpc_method_handler(
          servicer.GetEipChargeInfoAndSpec,
          request_deserializer=bill_dot_v1_dot_bill__pb2.GetChargeInfoAndSpecRequest.FromString,
          response_serializer=bill_dot_v1_dot_bill__pb2.GetEipChargeInfoAndSpecResponse.SerializeToString,
      ),
      'GetEbsChargeInfoAndSpec': grpc.unary_unary_rpc_method_handler(
          servicer.GetEbsChargeInfoAndSpec,
          request_deserializer=bill_dot_v1_dot_bill__pb2.GetChargeInfoAndSpecRequest.FromString,
          response_serializer=bill_dot_v1_dot_bill__pb2.GetEbsChargeInfoAndSpecResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'didi.cloud.bill.v1.Bill', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
